In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn import tree
from sklearn import model_selection
from sklearn import metrics
from sklearn import *
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, roc_auc_score, f1_score, make_scorer, silhouette_score, calinski_harabasz_score, davies_bouldin_score, rand_score, adjusted_rand_score, normalized_mutual_info_score, homogeneity_score, completeness_score, v_measure_score
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.mixture import GaussianMixture

In [ ]:
#определяем алгоритм кластеризации
km = KMeans(n_clusters=3, random_state=42)
#обучаем его на наших данных
km.fit_predict(X)
#вычисляем значение коэффициента силуэта
score = silhouette_score(X, km.labels_, metric='euclidean')

In [ ]:
#определяем алгоритм кластеризации
km = KMeans(n_clusters=3, random_state=42)
#обучаем его на наших данных
km.fit_predict(X)
#вычисляем значение коэффициента Калински — Харабаса
score = calinski_harabasz_score(X, km.labels_)

In [ ]:
#определяем алгоритм кластеризации
km = KMeans(n_clusters=3, random_state=42)
#обучаем его на наших данных
km.fit_predict(X)
#вычисляем значение коэффициента Дэвиса — Болдина
score = davies_bouldin_score(X, km.labels_)

Внутренняя мера	Интерпретация	Диапазон значений	Функция в библиотеке sklearn

Коэффициент силуэта	Мера того, насколько объект похож на объекты из своего собственного кластера по сравнению с объектами из других кластеров.	От -1 до 1: при качественной кластеризации значение близко к 1.	silhouette_score()

Индекс Калински — Харабаса	Показывает отношение между разбросом значений между кластерами и разбросом значений внутри кластеров. Оценка выше, когда кластеры плотные и хорошо разделены.	Любое неотрицательное значение. Чем больше значение, тем лучше.	calinski_harabasz_score()

Индекс Дэвиса — Болдина	Показывает среднюю «схожесть» между кластерами.	Не менее 0. Чем меньше значение, тем лучше.	davies_bouldin_score()

Внутрикластерное расстояние	Показывает, насколько плотно расположены объекты в кластерах.	Не менее 0. Чем меньше значение, тем лучше.	Не реализовано

Межкластерное расстояние	Показывает, насколько далеки друг от друга элементы из разных кластеров.	Не менее 0. Чем больше значение, тем лучше.	Не реализовано

In [ ]:
print(rand_score([1, 1, 1, 2, 2], [1, 1, 2, 2, 3]))

In [ ]:
print(adjusted_rand_score([1, 1, 1, 2, 2], [1, 1, 2, 2, 3]))

In [ ]:
normalized_mutual_info_score()

In [ ]:
homogeneity_score()

In [ ]:
completeness_score()

In [ ]:
v_measure_score()

МЕТРИКА	ИНТЕРПРЕТАЦИЯ И ПРИМЕНЕНИЕ	ДИАПАЗОН ЗНАЧЕНИЙ	ФУНКЦИЯ В МОДУЛЕ METRICS БИБЛИОТЕКИ SKLEARN

Однородность (homogeneity score)	Показывает, насколько однородны получившиеся кластеры. Если в кластере оказались элементы из другого кластера, значение метрики уменьшается.	1 — идеально однородные кластеры; 0 — кластеры максимально разнородные.	homogeneity_score

Полнота (completeness score)	Показывает, насколько кластер заполнен объектами, которые в действительности должны принадлежать к этому кластеру.	1 — идеальное значение; 0 — объекты, которые должны образовывать один кластер, разделились на большее количество кластеров.	completeness_score

V-мера (V-measure)	Комбинация метрик полноты и однородности кластеров.	1 — идеально полные и однородные кластеры; 0 — полученные кластеры неоднородные, количество кластеров слишком большое.	v_measure_score

Индекс Рэнда	Показывает долю объектов датасета, которые мы правильно определили в кластер.	1 — все объекты в предсказанном кластере попали в правильные кластеры.	rand_score

Нормализованная взаимная информация	Показывает, насколько разбиение согласуется с реальными метками.	1 — максимальная согласованность, все объекты находятся в правильных кластерах; 0 — случайное разбиение.	normalized_mutual_info_score

In [12]:
(2*0.7*0.35)/(0.7+0.35)

0.4666666666666667

In [13]:
path_train = r'C:\Users\troyd\OneDrive\Desktop\data\Physical Activity Data\train.txt'
path_train_label = r'C:\Users\troyd\OneDrive\Desktop\data\Physical Activity Data\train_labels.txt'
path_test = r'C:\Users\troyd\OneDrive\Desktop\data\Physical Activity Data\test.txt'
path_test_label = r'C:\Users\troyd\OneDrive\Desktop\data\Physical Activity Data\test_labels.txt'

In [14]:
X_train = np.loadtxt(path_train)
y_train = np.loadtxt(path_train_label)
 
X_test = np.loadtxt(path_test)
y_test = np.loadtxt(path_test_label)
X = np.concatenate((X_train, X_test))
y = np.concatenate((y_train, y_test))
X.shape

(10299, 561)

In [15]:
len(np.unique(y))

6

In [16]:
#определяем скейлер
scaler = StandardScaler()
#масштабируем данные
X_scaled = scaler.fit_transform(X)
#выводим нужное значение
X_scaled[0][0]

np.float64(0.2105338541767611)

In [17]:
#проходимся циклом по всем нужным нам значениям количества кластеров
for i in range(2,10):
	# обучаем модель k-means с текущим количеством кластеров
    km = KMeans(n_clusters = i , random_state = 42 ).fit(X_scaled)
	#предсказываем метки
    y_pred = km.labels_
	#выводим результат для коэффициента силуэта
    print (i, metrics.silhouette_score(X_scaled,  y_pred))
for i in range(2,10):
    km = KMeans(n_clusters = i , random_state = 42 ).fit(X_scaled)
    y_pred= km.labels_
    print (i, metrics.calinski_harabasz_score(X_scaled,y_pred))
for i in range(2,10):
    km = KMeans(n_clusters = i , random_state = 42 ).fit(X_scaled)
    y_pred = km.labels_
    print (i, metrics.davies_bouldin_score(X_scaled, y_pred))

2 0.39373247640770803
3 0.3165174060752721
4 0.2782645026686318
5 0.25967188010717684
6 0.11706978147952803
7 0.10120866778714624
8 0.09199222994561511
9 0.08267046481294246
2 7880.813903657111
3 5034.470017849821
4 3668.01737270831
5 2845.8388941647872
6 2504.685859086993
7 2171.068983512932
8 1890.890051976994
9 1685.013483142379
2 1.0707441822385657
3 1.7838205288134954
4 2.0464376750898374
5 2.266485003212643
6 2.52599900702495
7 2.6502858155881905
8 2.619035633846788
9 2.7593862241965237

In [18]:
#определяем модель k-means
model= KMeans(n_clusters=6, init='random', random_state=42)
#обучаем модель
model.fit(X_scaled)
#вычисляем значение однородности
print(homogeneity_score(y, model.labels_))
#вычисляем значение полноты
print(completeness_score(y, model.labels_))
#вычисляем значение скорректированного индекса Рэнда
print(adjusted_rand_score(y, model.labels_))

0.5406994702303469
0.5792825031740629
0.41962042580459846

In [20]:
#создаём таблицу сопряжённости
ct = pd.crosstab(y, model.labels_)
#определяем название активностей
ct.index = ['ходьба', 'подъём', 
            'спуск', 'сидение', 'стояние', 'лежание']
ct.columns = list(range(1,7))
ct

           1     2    3     4    5     6
ходьба   741   897    0     0   84     0
подъём   297  1236    2     0    9     0
спуск    882   310    0     0  214     0
сидение    0     1  447    91    0  1238
стояние    0     0  560     0    0  1346
лежание    0     5  329  1556    0    54

In [23]:
#определяем модель k-means
km= KMeans(n_clusters=2, init='random', random_state=42)
#обучаем модель
km.fit(X_scaled)

KMeans(init='random', n_clusters=2, random_state=42)

In [25]:
ctable = pd.crosstab(y, km.labels_)
ctable.index = ['ходьба', 'подъём', 
                'спуск', 'сидение', 'стояние', 'лежание']
ctable.columns = list(range(1,3))
ctable

            1     2
ходьба   1722     0
подъём   1536     8
спуск    1406     0
сидение     3  1774
стояние     0  1906
лежание    12  1932

In [26]:
metrics.completeness_score(y, km.labels_)

0.9795305596996312

In [27]:
ag = AgglomerativeClustering(n_clusters=2).fit(X_scaled)
print("Completeness: %0.3f" % metrics.completeness_score(y, ag.labels_))

Completeness: 1.000